modLoader = "javafml"
loaderVersion = "[37,)"
license = "CC0-1.0"

[[mods]]
modId = "delightfulchefs"
version = "${version}"
displayName = "Delightful Trades"
authors = "average_anime"
description = '''
New villagers + new trades. For Farmer's Delight and Create.
'''
logoFile = "../icon.png"

[[dependencies.delightfulchefs]]
modId = "forge"
mandatory = true
versionRange = "[41.0.22,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.delightfulchefs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"